-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 09:50:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema analysis_basketball
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `analysis_basketball` ;

-- -----------------------------------------------------
-- Schema analysis_basketball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analysis_basketball` DEFAULT CHARACTER SET utf8 ;
USE `analysis_basketball` ;

-- -----------------------------------------------------
-- Table `analysis_basketball`.`leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis_basketball`.`leagues` ;

CREATE TABLE IF NOT EXISTS `analysis_basketball`.`leagues` (
  `id_league` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_league`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analysis_basketball`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis_basketball`.`teams` ;

CREATE TABLE IF NOT EXISTS `analysis_basketball`.`teams` (
  `id_team` INT NOT NULL,
  `date` DATE NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `is_home` TINYINT NOT NULL,
  `total_points` INT NOT NULL,
  `q_1` INT NOT NULL,
  `q_2` INT NOT NULL,
  `q_3` INT NOT NULL,
  `q_4` INT NOT NULL,
  `over_time` TINYINT NOT NULL,
  `is_win` TINYINT NOT NULL,
  `leagues_id_league` INT NOT NULL,
  PRIMARY KEY (`id_team`, `leagues_id_league`),
  INDEX `fk_teams_leagues_idx` (`leagues_id_league` ASC) VISIBLE,
  CONSTRAINT `fk_teams_leagues`
    FOREIGN KEY (`leagues_id_league`)
    REFERENCES `analysis_basketball`.`leagues` (`id_league`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analysis_basketball`.`t_errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis_basketball`.`t_errors` ;

CREATE TABLE IF NOT EXISTS `analysis_basketball`.`t_errors` (
  `id_error` INT NOT NULL,
  `date` DATE NOT NULL,
  `home` VARCHAR(25) NOT NULL,
  `away` VARCHAR(25) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
