-- MySQL Script generated by MySQL Workbench
-- Thu May 11 00:10:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_mis_marcadores
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_mis_marcadores` ;

-- -----------------------------------------------------
-- Schema test_mis_marcadores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_mis_marcadores` DEFAULT CHARACTER SET utf8 ;
USE `test_mis_marcadores` ;

-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`matches` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`matches` (
  `id_match` INT NOT NULL,
  `date_match` DATE NOT NULL,
  `is_home` TINYINT NOT NULL,
  `total_points` INT NOT NULL,
  `q_1` INT NOT NULL,
  `q_2` INT NOT NULL,
  `q_3` INT NOT NULL,
  `q_4` INT NOT NULL,
  `over_time` TINYINT NOT NULL,
  `is_win` TINYINT NOT NULL,
  PRIMARY KEY (`id_match`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`leagues` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`leagues` (
  `id_league` INT NOT NULL,
  `name_league` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_league`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`t_errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`t_errors` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`t_errors` (
  `id_error` INT NOT NULL AUTO_INCREMENT,
  `league_error` VARCHAR(40) NOT NULL,
  `description_error` VARCHAR(150) NULL,
  PRIMARY KEY (`id_error`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`statistics` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`statistics` (
  `id_statistics` INT NOT NULL,
  `avg_gral` FLOAT(5,2) NULL,
  `mdn_gral` FLOAT(5,2) NULL,
  `max_gral` INT NULL,
  `min_gral` INT NULL,
  `avg_h` FLOAT(5,2) NULL,
  `mdn_h` FLOAT(5,2) NULL,
  `max_h` INT NULL,
  `min_h` INT NULL,
  `avg_a` FLOAT(5,2) NULL,
  `mdn_a` FLOAT(5,2) NULL,
  `max_a` INT NULL,
  `min_a` INT NULL,
  `avg_q1_h` FLOAT(5,2) NULL,
  `mdn_q1_h` FLOAT(5,2) NULL,
  `max_q1_h` INT NULL,
  `min_q1_h` INT NULL,
  `avg_q2_h` FLOAT(5,2) NULL,
  `mdn_q2_h` FLOAT(5,2) NULL,
  `max_q2_h` INT NULL,
  `min_q2_h` INT NULL,
  `avg_q3_h` FLOAT(5,2) NULL,
  `mdn_q3_h` FLOAT(5,2) NULL,
  `max_q3_h` INT NULL,
  `min_q3_h` INT NULL,
  `avg_q4_h` FLOAT(5,2) NULL,
  `mdn_q4_h` FLOAT(5,2) NULL,
  `max_q4_h` INT NULL,
  `min_q4_h` INT NULL,
  `avg_q1_a` FLOAT(5,2) NULL,
  `mdn_q1_a` FLOAT(5,2) NULL,
  `max_q1_a` INT NULL,
  `min_q1_a` INT NULL,
  `avg_q2_a` FLOAT(5,2) NULL,
  `mdn_q2_a` FLOAT(5,2) NULL,
  `max_q2_a` INT NULL,
  `min_q2_a` INT NULL,
  `avg_q3_a` FLOAT(5,2) NULL,
  `mdn_q3_a` FLOAT(5,2) NULL,
  `max_q3_a` INT NULL,
  `min_q3_a` INT NULL,
  `avg_q4_a` FLOAT(5,2) NULL,
  `mdn_q4_a` FLOAT(5,2) NULL,
  `max_q4_a` INT NULL,
  `min_q4_a` INT NULL,
  `teams_id_team_play` INT NOT NULL,
  PRIMARY KEY (`id_statistics`, `teams_id_team_play`),
  INDEX `fk_statistics_teams1_idx` (`teams_id_team_play` ASC) VISIBLE,
  CONSTRAINT `fk_statistics_teams1`
    FOREIGN KEY (`teams_id_team_play`)
    REFERENCES `test_mis_marcadores`.`matches` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`teams` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`teams` (
  `id_team` INT NOT NULL,
  `name_team` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`teams_has_leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`teams_has_leagues` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`teams_has_leagues` (
  `teams_id_team` INT NOT NULL,
  `leagues_id_league` INT NOT NULL,
  PRIMARY KEY (`teams_id_team`, `leagues_id_league`),
  INDEX `fk_team_has_leagues_leagues1_idx` (`leagues_id_league` ASC) VISIBLE,
  INDEX `fk_team_has_leagues_team1_idx` (`teams_id_team` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_leagues_team1`
    FOREIGN KEY (`teams_id_team`)
    REFERENCES `test_mis_marcadores`.`teams` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_leagues_leagues1`
    FOREIGN KEY (`leagues_id_league`)
    REFERENCES `test_mis_marcadores`.`leagues` (`id_league`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`teams_has_matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`teams_has_matches` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`teams_has_matches` (
  `teams_id_team` INT NOT NULL,
  `matches_id_match` INT NOT NULL,
  PRIMARY KEY (`teams_id_team`, `matches_id_match`),
  INDEX `fk_team_has_match_match1_idx` (`matches_id_match` ASC) VISIBLE,
  INDEX `fk_team_has_match_team1_idx` (`teams_id_team` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_match_team1`
    FOREIGN KEY (`teams_id_team`)
    REFERENCES `test_mis_marcadores`.`teams` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_match_match1`
    FOREIGN KEY (`matches_id_match`)
    REFERENCES `test_mis_marcadores`.`matches` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_mis_marcadores`.`links_leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_mis_marcadores`.`links_leagues` ;

CREATE TABLE IF NOT EXISTS `test_mis_marcadores`.`links_leagues` (
  `index_link` INT NOT NULL AUTO_INCREMENT,
  `link_league` VARCHAR(140) NULL,
  PRIMARY KEY (`index_link`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
